title: MNNIT CC 2021-22 Classes
description: This repository contains the codes, support links and other relevant materials for every class under Computer Club, MNNIT Allahabad.
image: sample_image.png
type: website
author: computer.club@mnnit.ac.in
favicon: "./cclogo_favicon.jpeg"
url: https://cc-mnnit.github.io

disqus_shortname: computer-club
